=== icobg123/ArgDb/uploads/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "http://example.com/example.json",
  "properties": {
    "analyst_email": {
      "default": "siwells@gmail.com",
      "description": "An explanation about the purpose of this instance.",
      "id": "/properties/analyst_email",
      "minLength": 5,
      "title": "The analyst_email schema",
      "type": "string"
    },
    "analyst_name": {
      "default": "Simon Wells",
      "description": "An explanation about the purpose of this instance.",
      "id": "/properties/analyst_name",
      "minLength": 5,
      "title": "The analyst_name schema",
      "type": "string"
    },
    "created": {
      "default": "2017-07-11T16:32:36",
      "description": "An explanation about the purpose of this instance.",
      "id": "/properties/created",
      "title": "The created schema",
      "type": "string"
    },
    "edges": {
      "id": "/properties/edges",
      "items": {
        "id": "/properties/edges/items",
        "properties": {
          "id": {
            "default": "d7bcef81-0d74-4ae5-96f9-bfb07031f1fa",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/edges/items/properties/id",
            "title": "The id schema",
            "type": "string"
          },
          "source_id": {
            "default": "49a786ce-9066-4230-8e18-42086882a160",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/edges/items/properties/source_id",
            "title": "The source_id schema",
            "type": "string"
          },
          "target_id": {
            "default": "9bfb7cdc-116f-47f5-b85d-ff7c5d329f45",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/edges/items/properties/target_id",
            "title": "The target_id schema",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "edited": {
      "default": "2017-07-11T16:32:36",
      "description": "An explanation about the purpose of this instance.",
      "id": "/properties/edited",
      "title": "The edited schema",
      "type": "string"
    },
    "id": {
      "default": "94a975db-25ae-4d25-93cc-1c07c932e2f8",
      "description": "An explanation about the purpose of this instance.",
      "id": "/properties/id",
      "title": "The id schema",
      "type": "string"
    },
    "metadata": {
      "id": "/properties/metadata",
      "properties": {
        "description": "This accepts anything, as long as it's valid JSON.",
        "title": "Empty Object"
      },
      "type": "object"
    },
    "nodes": {
      "id": "/properties/nodes",
      "items": {
        "id": "/properties/nodes/items",
        "properties": {
          "id": {
            "default": "9bfb7cdc-116f-47f5-b85d-ff7c5d329f45",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/nodes/items/properties/id",
            "title": "The id schema",
            "type": "string"
          },
          "metadata": {
            "id": "/properties/nodes/items/properties/metadata",
            "properties": {
              "description": "This accepts anything, as long as it's valid JSON.",
              "title": "Empty Object"
            },
            "type": "object"
          },
          "sources": {
            "id": "/properties/nodes/items/properties/sources",
            "items": {
              "description": "This accepts anything, as long as it's valid JSON.",
              "title": "Empty Object"
            },
            "type": "array"
          },
          "text": {
            "default": "The 'Hang Back' campaign video should not have been published, and should be withdrawn.",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/nodes/items/properties/text",
            "title": "The text schema",
            "type": "string"
          },
          "type": {
            "default": "atom",
            "description": "An explanation about the purpose of this instance.",
            "id": "/properties/nodes/items/properties/type",
            "title": "The type schema",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "resources": {
      "id": "/properties/resources",
      "items": {
        "description": "This accepts anything, as long as it's valid JSON.",
        "title": "Empty Object"
      },
      "type": "array"
    }
  },
  "required": [
    "resources",
    "id",
    "nodes",
    "edges",
    "created",
    "analyst_email",
    "analyst_name",
    "edited"
  ],
  "type": "object"
}

=== icobg123/ArgDb/uploads/sadFace.json
{
  "edited": "veniam voluptate sed",
  "analyst_name": "dolore non qui elit sunt",
  "analyst_email": "icara@abv.bg",
  "created": "consequat adipisicing ex proident voluptate",
  "edges": [
    {
      "source": "voluptate velit nisi eiusmod consectetur",
      "id": "ut commodo dolore laboris sit",
      "target": "labori"
    },
    {
      "source": "esse reprehenderit",
      "id": "fugiat est in",
      "target": "aliquip laborum eu"
    },
    {
      "source": "voluptate quis dolore in",
      "id": "in adipisicing",
      "target": "Duis aliquip tempor fugiat ad"
    },
    {
      "source": "dolor Lorem",
      "id": "Duis laboris cillum",
      "target": "est laboris voluptate dolore"
    }
  ],
  "nodes": [
    {
      "sources": [
        {
          "text": "id reprehenderit",
          "length": 34368693,
          "resource_id": "sunt",
          "offset": 1249330
        },
        {
          "text": "qui",
          "length": -9803922,
          "resource_id": "consectetur",
          "offset": 29607391
        }
      ],
      "type": "exercitation consequat in",
      "id": "enim elit in",
      "canonical_text": "enim"
    },
    {
      "sources": [
        {
          "text": "voluptate",
          "length": 87361190,
          "resource_id": "exercitation in Ut anim sint",
          "offset": 60910708
        },
        {
          "text": "dolor",
          "length": -12916350,
          "resource_id": "et consequat se",
          "offset": -57680106
        },
        {
          "text": "voluptate dolor mollit consectetur eu",
          "length": -1179942,
          "resource_id": "ut Ut",
          "offset": 96935431
        }
      ],
      "type": "",
      "id": "eu irure ullamco Excepteur",
      "canonical_text": "mollit cillum ea"
    }
  ],
  "id": "do commodo anim",
  "resources": [
    {
      "content": "in ",
      "type": "labore Ut adipisicing",
      "id": "irure ut amet eiusmod"
    },
    {
      "content": "",
      "type": "ad adipisicing",
      "id": "non officia dolore nisi"
    },
    {
      "content": "Lorem magna sed",
      "type": "sit",
      "id": "et tempor o"
    },
    {
      "content": "ut Ut anim labore",
      "type": "dolore",
      "id": "consequat dolore Excepteur id"
    },
    {
      "content": "Exc",
      "type": "velit ci",
      "id": "nostrud"
    }
  ],
  "metadata": {
    "some": "ut",
    "hello": "in cillum nostrud incididunt aliquip"
  }
}

=== icobg123/ArgDb/uploads/testJson.json
{
  "metadata": {
    "title": "Empty Object"
  },
  "resources": [
    {
      "description": "This accepts anything, as long as it's valid JSON.",
      "title": "Empty Object"
    },
    {
      "description": "This accepts anything, as long as it's valid JSON.",
      "title": "Empty Object"
    }
  ],
  "id": "T4Y6-0935-2tLB-mY5A",
  "nodes": [
    {
      "id": "65FP-j8yM-8305-42oP",
      "type": "scheme"
    },
    {
      "id": "C5y1-g2E1-6GDL-g4S7",
      "type": "scheme",
      "text": "quis nulla aliqua est"
    },
    {
      "id": "eCfb-b533-QwcH-67qK",
      "type": "scheme"
    },
    {
      "id": "8Q13-JiQ5-Aazb-dcxz",
      "type": "scheme",
      "text": "Excepteur",
      "sources": [
        {
          "description": "This accepts anything, as long as it's valid JSON.",
          "title": "Empty Object"
        },
        {
          "description": "This accepts anything, as long as it's valid JSON.",
          "title": "Empty Object"
        },
        {
          "description": "This accepts anything, as long as it's valid JSON.",
          "title": "Empty Object"
        }
      ]
    }
  ],
  "edges": [
    {
      "id": "75U2-s810-541Q-pV55",
      "target_id": "0Yd5-4VTM-4491-I902",
      "source_id": "37a6-7VIB-67RL-4NV5"
    }
  ],
  "created": "minim",
  "analyst_email": "8cF33@x4kelsE7PX.NFz43",
  "analyst_name": "adipisicing",
  "edited": "in"
}
